// <auto-generated />
using System;
using Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20210611134636_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Catalog.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("UnitsLeft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("pk_item");

                    b.ToTable("item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 636, DateTimeKind.Utc).AddTicks(4889),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Refined Granite Pants",
                            Price = 53m,
                            UnitsLeft = 17,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 636, DateTimeKind.Utc).AddTicks(9548)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3702),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Unbranded Steel Tuna",
                            Price = 56m,
                            UnitsLeft = 10,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3708)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3758),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Fresh Cheese",
                            Price = 53m,
                            UnitsLeft = 7,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3760)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3790),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Cotton Ball",
                            Price = 53m,
                            UnitsLeft = 15,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3792)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3821),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Intelligent Granite Hat",
                            Price = 52m,
                            UnitsLeft = 20,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3822)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3934),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Sleek Granite Fish",
                            Price = 52m,
                            UnitsLeft = 14,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3936)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3960),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Rubber Pants",
                            Price = 53m,
                            UnitsLeft = 13,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3962)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3997),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Rubber Hat",
                            Price = 50m,
                            UnitsLeft = 7,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(3999)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(4023),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Small Cotton Shirt",
                            Price = 50m,
                            UnitsLeft = 2,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(4025)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(4050),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Generic Soft Sausages",
                            Price = 50m,
                            UnitsLeft = 20,
                            UpdatedAt = new DateTime(2021, 6, 11, 13, 46, 35, 637, DateTimeKind.Utc).AddTicks(4052)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
