CREATE DATABASE IF NOT EXISTS `iam`;

CREATE DATABASE IF NOT EXISTS `debug:catalog`;
CREATE DATABASE IF NOT EXISTS `debug:cart`;
CREATE DATABASE IF NOT EXISTS `debug:order`;
CREATE DATABASE IF NOT EXISTS `debug:tenant-manager`;

CREATE DATABASE IF NOT EXISTS `one:catalog`;
CREATE DATABASE IF NOT EXISTS `one:cart`;
CREATE DATABASE IF NOT EXISTS `one:order`;
CREATE DATABASE IF NOT EXISTS `one:tenant-manager`;

CREATE DATABASE IF NOT EXISTS `two:catalog`;
CREATE DATABASE IF NOT EXISTS `two:cart`;
CREATE DATABASE IF NOT EXISTS `two:order`;
CREATE DATABASE IF NOT EXISTS `two:tenant-manager`;
