version: '3.4'

services:
  catalog-api:
    build:
        context: .
        dockerfile: Services/Catalog/Dockerfile
    environment:
      # For development purposes
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=db;Database=prototype_one;User=root;Password=development"
    ports:
      - "50496:80"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=prototype_one
      - MYSQL_ROOT_PASSWORD=development
    ports:
      - "4000:3306"
    volumes: 
      - db-data:/var/lib/mysql

volumes:
  db-data:
    # external: true