version: '3.4'

services:
  #MySQL 
  mysql:
    image: mysql

  adminer:
    image: adminer
    depends_on: 
      - mysql

  #Rabbit MQ
  rabbitmq:
    image: rabbitmq:3-management-alpine

  #API Gateway
  webcore-api-gateway:
    image: ${DOCKER_REGISTRY-}webcoreapi
    build:
      context: .
      dockerfile: ApiGateways/WebCoreAPI/Dockerfile
    depends_on:
      - catalog-api
      - cart-api
      - order-api

  #Microservices
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    depends_on: 
      - mysql

  cart-api:
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: Services/Cart/Dockerfile
    depends_on: 
      - mysql

  order-api:
    image: ${DOCKER_REGISTRY-}order
    build:
      context: .
      dockerfile: Services/Order/Dockerfile
    depends_on: 
      - mysql
