version: '3.4'

services:
  mysql:
    image: mysql

  adminer:
    image: adminer
    depends_on: 
      - mysql
    
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    depends_on: 
      - mysql

  cart:
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: Services/Cart/Dockerfile
    depends_on: 
      - mysql

  order:
    image: ${DOCKER_REGISTRY-}order
    build:
      context: .
      dockerfile: Services/Order/Dockerfile
    depends_on: 
      - mysql
